### ISSUE TITLE
Race condition on LogLineReader.ReadLogLines and Shuttle.Land

### ISSUE THREAD

**Issue by fabiokung** [heroku/log-shuttle#49]
[`Shuttle.Land` closes shared channels](https://github.com/heroku/log-shuttle/blob/master/shuttle.go#L88) while [Readers may still be trying to write to them](https://github.com/heroku/log-shuttle/blob/master/reader.go#L45). This causes a panic at runtime.

`Shuttle.Land` needs to notify and/or synchronize with all its readers, stopping them before closing the channel.

/cc @sclasen

**Comment by freeformz** [comment]
How are you using it that this is required?

IMO synchronization with the readers should be handled by the task calling Land(), not Land(). This is the whole reason why ReadLogLines blocks until the io.ReadCloser is closed. This is also trivially implementable by users of the lib that want it.

With that said I could be convinced that adding a new method (AddReader or what not) that does this. I'm just currently skeptical.

**Comment by freeformz** [comment]
After a bit of internal discussion I am convinced because I was wrong and the API is a little weird. I'll take a look and propose some cleanups.

**Comment by fabiokung** [comment]
Sweet. Thanks!
