### ISSUE TITLE
Log-Shuttle 0.13.0/0.13.1 Release not hosted on Docker Hub

### ISSUE THREAD

**Issue by gabe-ochoa** [heroku/log-shuttle#65]
I am attempting to use log-shuttle with kinesis and want to make use multiple shards but 0.13.x has not been built into a container and hosted on Docker Hub. 

I've built 0.13.1 and self-hosted for the time being but could we get a release pushed up to Docker Hub?

Thanks!
Gabe

**Comment by freeformz** [comment]
Docker versions are also now pushed by travis. I manually checked out the v0.13.x tags, built the images and pushed them to docker hub.

Thanks!

**Comment by gabe-ochoa** [comment]
Thanks @freeformz!
