### ISSUE TITLE
Log-shuttle binary not copied into docker container for 0.15.0 and 0.16.0 releases

### ISSUE THREAD

**Issue by gabe-ochoa** [heroku/log-shuttle#74]
Hi!
I'm attempting to run the 0.16.0 release of the log-shuttle in the container tag 0.16.0 on docker hub. 

When I run either the 0.15.0 or 0.16.0 release containers docker says the log-shuttle binary is not located at the entry point:
```
docker run -it --rm heroku/log-shuttle:0.16.0
docker: Error response from daemon: Container command '/bin/log-shuttle' not found or does not exist..
```
Looking at the Dockerfile there is a comment that mentions that the binary is copied in to the container after being pre-built. https://github.com/heroku/log-shuttle/blob/master/Dockerfile#L5

From the error it looks like the log-shuttle binary didn't make it into the container or the location changed and the entry point needs to be updated. 

Thanks for the help!

**Comment by gabe-ochoa** [comment]
If it helps, I was able to build the `v0.16.0` tag locally into a docker container using the docker steps in the make file through `make docker` and that container works as expected.

**Comment by freeformz** [comment]
@gabe-ochoa I've re-pushed those tags. I'll probably have to turn off auto-builds on docker hub or come up with another way to integrate with that.

**Comment by gabe-ochoa** [comment]
@freeformz Thanks for the quick response. I've pulled down the new container and it looks good. Thanks! I'll close the issue.
